### ISSUE TITLE
neo-java SDK Version Deprecated

### ISSUE THREAD

**Issue by lucasheim** [SAP/cloud-s4-sdk-pipeline-docker#10]
On s4sdk-docker-neo-cli dockerfile, which is used as a default for Piper's neoDeploy step, the SDK version used is still 2.161.3, which is already deprecated in SAP's documentation for dev tools: https://tools.hana.ondemand.com/#cloud . I think it should be updated to Java EE 7 Web Profile TomEE 7, or at least to the last version 2.161.9.

There's even a warning about this when trying to deploy with piper:
![image](https://user-images.githubusercontent.com/13325346/65266542-a90dcd80-dae9-11e9-8221-bcebc8dbaf28.png)

**Comment by fwilhe** [comment]
Hi @lucasheim, thanks for reporting the issue.

We're about to switch to the new `ppiper/neo-cli` image soon which already was updated to the new version, see here https://github.com/SAP/devops-docker-neo-cli for details.

If you have an urgent need to use the new version, you can already configure your pipeline to use the new image, otherwise it will be updated once we did that switch.

Kind regards

Florian
